import Head from 'next/head';
import Link from 'next/link';

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page-home">
        <div className="profile-photo-section">
          <img src="/images/anoop.jpg" width="150px" height="150px" className="profile-photo"/>
        </div>
        <div className="name">
          anoop
        </div>
        <div className="title">
          software programmer
        </div>

        <section className="nav">
          <nav>
            <Link href="/notes">
              <a>notes</a>
            </Link>
            <Link href="/about">
              <a>about</a>
            </Link>
            <Link href="/startups">
              <a>startups</a>
            </Link>
            <Link href="/opensource">
              <a>opensource</a>
            </Link>
            <Link href="/work">
              <a>work</a>
            </Link>
          </nav>
        </section>
      </main>

      <footer>
      </footer>
    </>
  );
};
